example:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PORT', 5432) | int }}"
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      pass: "{{ env_var('DBT_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('DBT_DATABASE', 'postgres') }}"
      schema: public

  target: dev
